sudo: false
language: java
jdk:
- openjdk8
script:
- test/run.sh
notifications:
  email:
    recipients:
      - sakthivel.sivaprakasam@cgi.com
      - deepika.ramraj@cgi.com
    on_success: always # default: change
    on_failure: always # default: always